using System.Web;
using Flurl;

namespace Click2Approve.Application.Helpers;

/// <summary>
/// Represents a set of static methods for URI handling.
/// </summary>
public static class UriHelpers
{
    /// <summary>
    /// Replaces the confirmation link generated by Identity framework with the one that matches UI routes.
    /// </summary>
    public static Uri GetDerivedEmailConfirmationLink(Uri confirmationLink, Uri? uiBaseUri, string? uiAppPath = null)
    {
        var userId = HttpUtility.ParseQueryString(confirmationLink.Query).Get("userId")
            ?? throw new ArgumentException("Confirmation link is missing the userId query parameter.", nameof(confirmationLink));
        var code = HttpUtility.ParseQueryString(confirmationLink.Query).Get("code")
            ?? throw new ArgumentException("Confirmation link is missing the code query parameter.", nameof(confirmationLink));
        return GetUiUri(uiBaseUri, uiAppPath, "confirmEmail")
            .SetQueryParam("userId", userId)
            .SetQueryParam("code", code)
            .ToUri();
    }

    public static Uri GetDerivedPasswordResetLink(string email, string resetCode, Uri? uiBaseUri, string? uiAppPath = null)
    {
        return GetUiUri(uiBaseUri, uiAppPath, "resetPassword")
            .SetQueryParam("email", email)
            .SetQueryParam("code", resetCode)
            .ToUri();
    }

    public static Url GetUiUri(Uri? uiBaseUri, string? uiAppPath, string route)
    {
        uiBaseUri ??= new Uri(string.Empty, UriKind.Relative);
        var url = uiBaseUri.ToString().TrimEnd('/');

        if (!string.IsNullOrWhiteSpace(uiAppPath))
        {
            url = url.AppendPathSegment(uiAppPath.Trim('/'));
        }

        return url.AppendPathSegment(route.Trim('/'));
    }
}
