using System.Web;
using Flurl;

namespace click2approve.WebAPI.Helpers;

/// <summary>
/// Represents a set of static methods for URI handling.
/// </summary>
public static class UriHelpers
{
    /// <summary>
    /// Replaces the confirmation link generated by Identity framework with the one that matches UI routes.
    /// </summary>
    public static Uri GetDerivedEmailConfirmationLink(Uri confirmationLink, Uri? uiBaseUri)
    {
        uiBaseUri ??= new Uri("");
        var userId = HttpUtility.ParseQueryString(confirmationLink.Query).Get("userId");
        var code = HttpUtility.ParseQueryString(confirmationLink.Query).Get("code");
        if (userId == null)
        {
            throw new ArgumentException("Missing query parameter", userId);
        }
        if (code == null)
        {
            throw new ArgumentException("Missing query parameter", code);
        }
        return uiBaseUri
            .AppendPathSegment("confirmEmail")
            .SetQueryParam("userId", userId)
            .SetQueryParam("code", code)
            .ToUri();
    }

    public static Uri GetDerivedPasswordResetLink(string email, string resetCode, Uri? uiBaseUri)
    {
        uiBaseUri ??= new Uri("");
        return uiBaseUri
            .AppendPathSegment("resetPassword")
            .SetQueryParam("email", email)
            .SetQueryParam("code", resetCode)
            .ToUri();
    }
}
