using System.Web;

namespace click2approve.WebAPI.Helpers;

/// <summary>
/// Represents a set of static methods for URI handling.
/// </summary>
public static class UriHelpers
{
    /// <summary>
    /// Replaces the confirmation link generated by Identity framework with the one that matches UI routes.
    /// </summary>
    public static Uri GetDerivedEmailConfirmationLink(Uri confirmationLink, Uri? uiBaseUri)
    {
        uiBaseUri ??= new Uri("");
        var userId = HttpUtility.ParseQueryString(confirmationLink.Query).Get("userId");
        var code = HttpUtility.ParseQueryString(confirmationLink.Query).Get("code");
        if (userId == null)
        {
            throw new ArgumentException("Missing query parameter", userId);
        }
        if (code == null)
        {
            throw new ArgumentException("Missing query parameter", code);
        }
        return new Uri(uiBaseUri, $"confirmEmail?userId={userId}&code={code}");
    }

    public static Uri GetDerivedPasswordResetLink(string email, string resetCode, Uri? uiBaseUri)
    {
        uiBaseUri ??= new Uri("");
        return new Uri(uiBaseUri, $"resetPassword?email={email}&code={resetCode}");
    }
}
